### ISSUE TITLE
【提问示例】如何waive学校保险？

### ISSUE THREAD

**Issue by dannierl** [elviswxy/SCU_CSA_Guidebook#1]
请问waive学校保险有什么要求？

**Comment by dannierl** [comment]
学校保险除非在美国有直系亲属，学生跟随直系亲属的保险，才可以向学校申请Waive，其余情况不可以更换或者Waive。详情参考：[https://www.scu.edu/cowell/insurance/](https://www.scu.edu/cowell/insurance/)

**Comment by dannierl** [comment]
> 学校保险除非在湾区有直系亲属，学生跟随直系亲属的保险，才可以向学校申请Waive，其余情况不可以更换或者Waive。详情参考：https://www.scu.edu/cowell/insurance/

如果对回复有更多疑惑，可以点Comments右上角的进行quote reply

**Comment by carry980828** [comment]
> > 学校保险除非在湾区有直系亲属，学生跟随直系亲属的保险，才可以向学校申请Waive，其余情况不可以更换或者Waive。详情参考：https://www.scu.edu/cowell/insurance/
> 
> 如果对回复有更多疑惑，可以点Comments右上角的进行quote reply

普通感冒挂吊瓶这种门诊保险给报吗，具体的报销流程是怎样的呢，是需要先自己垫付还是医院会直接跟保险公司联系付款

**Comment by dannierl** [comment]
> > > 学校保险除非在湾区有直系亲属，学生跟随直系亲属的保险，才可以向学校申请Waive，其余情况不可以更换或者Waive。详情参考：https://www.scu.edu/cowell/insurance/
> > 
> > 
> > 如果对回复有更多疑惑，可以点Comments右上角的进行quote reply
> 
> 普通感冒挂吊瓶这种门诊保险给报吗，具体的报销流程是怎样的呢，是需要先自己垫付还是医院会直接跟保险公司联系付款

延伸出来的新问题以后可以单独开一个issue
