### ISSUE TITLE
选课review收集链接

### ISSUE THREAD

**Issue by theRealCourseEvaluationSCU** [elviswxy/SCU_CSA_Guidebook#15]
- github地址：https://github.com/theRealCourseEvaluationSCU/SCU_MSCSE_Course_Evaluate
- 麻烦请直接refer to这个链接，内容就不和csa的guidebook合并啦，这个算我和身边同学的个人项目，免责声明里有写到不和组织合作的。感谢理解

**Comment by elviswxy** [comment]
已增加refer链接 感谢分享
