### ISSUE TITLE
关于美国驾照的一些疑问

### ISSUE THREAD

**Issue by mementolim** [elviswxy/SCU_CSA_Guidebook#3]
请问在美国考驾照需要报名驾校么？如果在国内拿到驾照去那里可以不学习直接考试么？流程是怎么样的呢？谢谢！

**Comment by yanjieren16** [comment]
1.不需要报名驾校。
2.可以DMV直接预约笔试+上路考试。（国内没有驾照也可以直接预约考试

**Comment by elviswxy** [comment]
补充一些：

1. 开车首先还是安全第一，所以请根据自己在国内的驾驶熟练程度来决定这边的上手难易程度。
2. 加州笔试每场容易预约，路考可能个人预约会需要排队，如果想尽快预约，也可以找一些第三方预约的人员，他们专门做带你熟悉考试路线以及预约路考的生意。
3. CA 驾照考试过程可参考：[这里](https://www.guruin.com/articles/611)
4. 网上找的CA笔试题目可参考：[这里](https://pass-dmv-test.com/quiz-1-zh.html)
