### ISSUE TITLE
关于美国通讯方式的一些疑问

### ISSUE THREAD

**Issue by mementolim** [elviswxy/SCU_CSA_Guidebook#4]
请问不在美国的情况下如果投递简历需要填写美国的地址和手机号呢？
在国内可以购买美国手机卡么？能够收到美国的电话么？飞机降落之后可以直接使用套餐里的流量么？哪个运营商比较推荐呢？
谢谢！

**Comment by dannierl** [comment]
1.淘宝可以买到，只要在国内能收短信，就可以用买到的号码注册Google Voice。简历上可填写Google Voice的号码
2.美国的号码是可以在运营商之间随意转换的，操作比较简单
3.买手机卡之前最好查一下自己的手机是否兼容对应运营商的网络

**Comment by dannierl** [comment]
[如何选择移动运营商及套餐](https://www.uscreditcardguide.com/how-to-choose-your-wireless-provider-and-plan/)

**Comment by dannierl** [comment]
我之前在国内用过这家虚拟运营商的卡
![image](https://user-images.githubusercontent.com/16151567/125156369-efe31200-e119-11eb-89b5-9c371ba0973c.png)

**Comment by dannierl** [comment]
另外可以youtube搜索一下: 美国 短信

**Comment by mementolim** [comment]
> 1.淘宝可以买到，只要在国内能收短信，就可以用买到的号码注册Google Voice。简历上可填写Google Voice的号码
> 2.美国的号码是可以在运营商之间随意转换的，操作比较简单
> 3.买手机卡之前最好查一下自己的手机是否兼容对应运营商的网络

请问一定要填写google voice 号码么，因为大部分商家都表示电话卡不能支持google voice,如果只是能接电话可以写在简历上吗？

**Comment by dannierl** [comment]
> > 1.淘宝可以买到，只要在国内能收短信，就可以用买到的号码注册Google Voice。简历上可填写Google Voice的号码
> 
> > 2.美国的号码是可以在运营商之间随意转换的，操作比较简单
> 
> > 3.买手机卡之前最好查一下自己的手机是否兼容对应运营商的网络
> 
> 
> 
> 请问一定要填写google voice 号码么，因为大部分商家都表示电话卡不能支持google voice,如果只是能接电话可以写在简历上吗？

你可能理解错我的意思了。
1.Google Voice注册时需要一个额外的号码作为验证，这个号码可以在淘宝上买
2.Google Voice注册完成后自动生成一个新号号码，只要能翻墙，这个号码就可以收发短信接打电话
