### ISSUE TITLE
电话卡的问题

### ISSUE THREAD

**Issue by Eyjan-Huang** [elviswxy/SCU_CSA_Guidebook#9]
Hello前辈，

前些天看见群里在讨论，但是刷完就过去了不好找记录，希望能在这个项目里系统性回答一下。

想问一下电话卡是来之前就办好还是来之后再办更好呢？而且听说好像有几个人合拼的会更便宜。以及能简单介绍一下哪家公司合适以及的具体使用情况吗？

比如：
推荐 XX公司的 XX套餐，这个套餐的价格是XX $/Month，流量限制是 XX Gb/Month。

感谢感谢🙏！

**Comment by dannierl** [comment]
[#4 ](https://github.com/elviswxy/SCU_CSA_Guidebook/issues/4#issuecomment-877590990) 里面我贴了一个链接，里面讲得很清楚了。以后问之前麻烦多读下已有的东西哈。
Verizon和ATT的自家的post paid service信号比较好，但是贵，合拼会便宜一点点点。如果使用需求不大的话，其实用一些post paid service会更划算。比如用Verizon网络的虚拟运营商Visible，虽然比不上V自家的信号，但性价比也非常不错了。
